name: v6
recipe: lamp
config:
  webroot: .
  config: 
    php: php.ini
services:
  node:
    type: node
    overrides:
      ports: [3000:3000, 3001:3001]
    build: 
      - npm install
    command: npm start
tooling:
  npm:
    service: node