name: boilerplate
recipe: lemp
config:
  webroot: .
services:
  node:
    type: node
    overrides:
      ports: [3000:3000, 3001:3001]
    build: 
      - npm install
    command: npm start
tooling:
  npm:
    service: node